foodgram/urls.py
from django.conf import settings
from django.conf.urls import handler404
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.flatpages import views
from django.urls import include, path


handler404 = 'recipes.views.page_not_found'  # noqa

urlpatterns = [
    path('', include('recipes.urls')),
    path('about/', include("django.contrib.flatpages.urls")),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
]

urlpatterns += [
    path("about/about-author/", views.flatpage,
         {"url": "/about-author/"}, name="about-author"),
    path("about/about-spec/", views.flatpage,
         {"url": "/about-spec/"}, name="about-spec"),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

recipes/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('profile/<int:user_id>', views.profile, name='profile'),
    path('favorites', views.FavoriteView.as_view(), name='favorite'),
    path('favorites/<int:recipe_id>', views.delete_favorite,
         name='delete_favorite'),
    path('my_subscriptions', views.get_subscriptions, name='my_subscriptions'),
    path('subscriptions', views.subscription, name='subscription'),
    path('subscriptions/<int:author_id>', views.delete_subscription,
         name='delete_subscription'),
    path('recipes/new', views.new_recipe, name='new_recipe'),
    path('recipes/<int:recipe_id>', views.recipe_detail,
         name='recipe'),
    path('recipes/<int:recipe_id>/edit', views.edit_recipe,
         name='edit_recipe'),
    path('recipes/<int:recipe_id>/delete', views.delete_recipe,
         name='delete_recipe'),
    path('purchases', views.PurchaseView.as_view(), name='purchases'),
    path('purchases/<int:recipe_id>', views.delete_purchase,
         name='delete_purchase'),
    path('shoplist', views.send_shop_list, name='shop-list'),
    path('ingredients', views.get_ingredients, name='ingredients'),
]

users/urls.py
from django.urls import path

from .views import SignUp


urlpatterns = [
    path('signup', SignUp.as_view(), name='signup'),
]

recipes/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.core.exceptions import ObjectDoesNotExist


User = get_user_model()


class Product(models.Model):
    title = models.CharField(max_length=255, verbose_name='Название продукта')
    unit = models.CharField(max_length=255, verbose_name='Единицы измерения')

    def __str__(self):
        return f'{self.title}, {self.unit}'


class Tag(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название тега')
    slug = models.SlugField(verbose_name='Слаг тега')

    def __str__(self):
        return f'{self.name}'


class RecipeManager(models.Manager):
    def tag_filter(self, tags):
        if tags:
            return super().get_queryset().prefetch_related(
                'author', 'tags'
            ).filter(
                tags__slug__in=tags
            ).distinct()
        else:
            return super().get_queryset().prefetch_related(
                'author', 'tags'
            ).all()


class Recipe(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               verbose_name='Автор рецепта',
                               related_name='recipe_author')
    name = models.CharField(max_length=255, verbose_name='Название рецепта')
    description = models.TextField(verbose_name='Описание рецепта')
    image = models.ImageField(upload_to='recipes/',
                              verbose_name='Изображение блюда')
    tags = models.ManyToManyField(Tag, verbose_name='Теги', blank=True)
    ingredients = models.ManyToManyField(
        Product, through='Ingredient', related_name='recipe_ingredients')
    cook_time = models.IntegerField(verbose_name='Время приготовления')
    pub_date = models.DateTimeField(
        auto_now_add=True, verbose_name='Время публикации', db_index=True)

    recipes = RecipeManager()

    class Meta:
        ordering = ('-pub_date',)

    def __str__(self):
        return f'{self.name}'


class Ingredient(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Product, on_delete=models.CASCADE)
    amount = models.FloatField(verbose_name='Количество ингредиента')

    class Meta:
        unique_together = ('ingredient', 'amount', 'recipe')

    def __str__(self):
        return f'{self.amount}'


class PurchaseManager(models.Manager):
    def counter(self, user):
        try:
            return super().get_queryset().get(user=user).recipes.count()
        except ObjectDoesNotExist:
            return 0

    def get_purchases_list(self, user):
        try:
            return super().get_queryset().get(user=user).recipes.all()
        except ObjectDoesNotExist:
            return []

    def get_user_purchase(self, user):
        try:
            return super().get_queryset().get(user=user)
        except ObjectDoesNotExist:
            purchase = Purchase(user=user)
            purchase.save()
            return purchase


class Purchase(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    recipes = models.ManyToManyField(Recipe)

    purchase = PurchaseManager()


class FavoriteManager(models.Manager):
    def get_favorites(self, user):
        try:
            return super().get_queryset().get(user=user).recipes.all()
        except ObjectDoesNotExist:
            return []

    def get_tag_filtered(self, user, tags):
        try:
            recipes = super().get_queryset().get(user=user).recipes.all()
            if tags:
                return recipes.prefetch_related(
                    'author', 'tags'
                ).filter(
                    tags__slug__in=tags
                ).distinct()
            else:
                return recipes.prefetch_related(
                    'author', 'tags'
                ).all()
        except ObjectDoesNotExist:
            return []

    def get_user(self, user):
        try:
            return super().get_queryset().get(user=user)
        except ObjectDoesNotExist:
            favorite_user = Favorite(user=user)
            favorite_user.save()
            return favorite_user


class Favorite(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    recipes = models.ManyToManyField(Recipe)

    favorite = FavoriteManager()

recipes/forms.py
from django import forms

from .models import Recipe, Tag


class RecipeForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple(attrs={'class': 'tags__checkbox'}),
        to_field_name='slug',
        required=False
    )

    class Meta:
        model = Recipe
        fields = ('name', 'cook_time', 'tags',
                  'description', 'image',)
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form__input'}),
            'cook_time': forms.NumberInput(
                attrs={'class': 'form__input',
                       'id': 'id_time',
                       'name': 'time'}),
            'description': forms.Textarea(attrs={'class': 'form__textarea',
                                                 'rows': '8'}),
        }
        labels = {
            'image': 'Загрузить фото'
        }

recipes/views.py
import json
from urllib.parse import unquote

from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.core.paginator import Paginator
from django.db.models import Sum
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.http import (require_GET, require_http_methods,
                                          require_POST)
from users.models import Subscription

from .forms import RecipeForm
from .models import Favorite, Ingredient, Product, Purchase, Recipe, Tag, User


def _extend_context(context, user):
    context['purchase_list'] = Purchase.purchase.get_purchases_list(user)
    context['favorites'] = Favorite.favorite.get_favorites(user)
    return context


def _add_subscription_status(context, user, author):
    context['is_subscribed'] = Subscription.objects.filter(
        user=user, author=author
    ).exists()
    return context


@require_GET
def index(request):
    tags = request.GET.getlist('tag')
    recipe_list = Recipe.recipes.tag_filter(tags)
    paginator = Paginator(recipe_list, 6)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {
        'all_tags': Tag.objects.all(),
        'page': page,
        'paginator': paginator
    }
    user = request.user
    if user.is_authenticated:
        context['active'] = 'recipe'
        _extend_context(context, user)
    return render(request, 'index.html', context)


@require_GET
def profile(request, user_id):
    profile = get_object_or_404(User, id=user_id)
    tags = request.GET.getlist('tag')
    recipes_list = Recipe.recipes.tag_filter(tags)
    paginator = Paginator(recipes_list.filter(author=profile), 6)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {
        'all_tags': Tag.objects.all(),
        'profile': profile,
        'page': page,
        'paginator': paginator
    }
    # Если юзер авторизован, добавляет в контекст список
    # покупок и избранное
    user = request.user
    if user.is_authenticated:
        _add_subscription_status(context, user, profile)
        _extend_context(context, user)
    return render(request, 'profile.html', context)


@require_GET
def recipe_detail(request, recipe_id):
    recipe = get_object_or_404(Recipe, id=recipe_id)
    context = {
        'recipe': recipe,
    }
    user = request.user
    if user.is_authenticated:
        _add_subscription_status(context, user, recipe.author)
        _extend_context(context, user)
    return render(request, 'recipe_detail.html', context)


class FavoriteView(View):
    model = Favorite

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_queryset(self):
        tags = self.request.GET.getlist('tag')
        user = self.request.user
        queryset = self.model.favorite.get_tag_filtered(user, tags)
        return queryset

    def get(self, request):
        paginator = Paginator(self.get_queryset(), 6)
        page_number = request.GET.get('page')
        page = paginator.get_page(page_number)
        purchase_list = Purchase.purchase.get_purchases_list(request.user)
        context = {
            'all_tags': Tag.objects.all(),
            'purchase_list': purchase_list,
            'active': 'favorite',
            'paginator': paginator,
            'page': page
        }
        return render(request, 'favorites.html', context)

    def post(self, request):
        json_data = json.loads(request.body.decode())
        recipe_id = json_data['id']
        recipe = get_object_or_404(Recipe, id=recipe_id)
        data = {'success': 'true'}
        favorite = Favorite.favorite.get_user(request.user)
        is_favorite = favorite.recipes.filter(id=recipe_id).exists()
        if is_favorite:
            data['success'] = 'false'
        else:
            favorite.recipes.add(recipe)
        return JsonResponse(data)


@login_required(login_url='auth/login/')
@require_http_methods('DELETE')
def delete_favorite(request, recipe_id):
    recipe = get_object_or_404(Recipe, id=recipe_id)
    data = {'success': 'true'}
    try:
        favorite = Favorite.favorite.get(user=request.user)
    except ObjectDoesNotExist:
        data['success'] = 'false'
    if not favorite.recipes.filter(id=recipe_id).exists():
        data['success'] = 'false'
    favorite.recipes.remove(recipe)
    return JsonResponse(data)


@login_required(login_url='auth/login/')
@require_GET
def get_subscriptions(request):
    try:
        subscriptions = Subscription.objects.filter(
            user=request.user
        ).order_by('pk')
    except ObjectDoesNotExist:
        subscriptions = []
    page_num = request.GET.get('page')
    paginator = Paginator(subscriptions, 6)
    page = paginator.get_page(page_num)
    context = {
        'active': 'subscription',
        'paginator': paginator,
        'page': page,
    }
    return render(request, 'subscriptions.html', context)


@login_required(login_url='auth/login/')
@require_POST
def subscription(request):
    json_data = json.loads(request.body.decode())
    author = get_object_or_404(User, id=json_data['id'])
    is_exist = Subscription.objects.filter(
        user=request.user, author=author).exists()
    data = {'success': 'true'}
    if is_exist:
        data['success'] = 'false'
    else:
        Subscription.objects.create(user=request.user, author=author)
    return JsonResponse(data)


@login_required(login_url='auth/login/')
@require_http_methods('DELETE')
def delete_subscription(request, author_id):
    author = get_object_or_404(User, id=author_id)
    data = {'success': 'true'}
    follow = Subscription.objects.filter(
        user=request.user, author=author)
    if not follow:
        data['success'] = 'false'
    follow.delete()
    return JsonResponse(data)


class PurchaseView(View):
    model = Purchase

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_queryset(self):
        queryset = self.model.purchase.get_purchases_list(self.request.user)
        return queryset

    def get(self, request):
        recipes_list = self.get_queryset()
        context = {
            'recipes_list': recipes_list,
            'active': 'purchase'
        }
        return render(request, 'purchases.html', context)

    def post(self, request):
        json_data = json.loads(request.body.decode())
        recipe_id = json_data['id']
        recipe = get_object_or_404(Recipe, id=recipe_id)
        purchase = Purchase.purchase.get_user_purchase(user=request.user)
        data = {
            'success': 'true'
        }
        if not purchase.recipes.filter(id=recipe_id).exists():
            purchase.recipes.add(recipe)
            return JsonResponse(data)
        data['success'] = 'false'
        return JsonResponse(data)


@login_required(login_url='auth/login/')
@require_http_methods('DELETE')
def delete_purchase(request, recipe_id):
    recipe = get_object_or_404(Recipe, id=recipe_id)
    data = {
        'success': 'true'
    }
    try:
        purchase = Purchase.purchase.get(user=request.user)
    except ObjectDoesNotExist:
        data['success'] = 'false'
    if not purchase.recipes.filter(id=recipe_id).exists():
        data['success'] = 'false'
    purchase.recipes.remove(recipe)
    return JsonResponse(data)


@login_required(login_url='auth/login/')
@require_GET
def send_shop_list(request):
    user = request.user
    ingredients = Ingredient.objects.select_related(
        'ingredient'
    ).filter(
        recipe__purchase__user=user
    ).values(
        'ingredient__title', 'ingredient__unit'
    ).annotate(total=Sum('amount'))
    filename = f'{user.username}_list.txt'
    products = [
        (f'+ {i["ingredient__title"]} ({i["ingredient__unit"]}) -'
         f' {i["total"]}')
        for i in ingredients]
    content = '  Продукт (единицы) - количество \n \n' + '\n'.join(products)
    response = HttpResponse(content, content_type='text/plain')
    response['Content-Disposition'] = f'attachment; filename={filename}'
    return response


@login_required(login_url='auth/login/')
@require_http_methods(['GET', 'POST'])
def new_recipe(request):
    context = {
        'active': 'new_recipe',
        'page_title': 'Создание рецепта',
        'button_label': 'Создать рецепт',
    }
    # GET-запрос на страницу создания рецепта
    if request.method == 'GET':
        form = RecipeForm()
        context['form'] = form
        return render(request, 'recipe_form.html', context)
    # POST-запрос с данными из формы создания рецепта
    elif request.method == 'POST':
        form = RecipeForm(request.POST, files=request.FILES or None)
        if not form.is_valid():
            context['form'] = form
            return render(request, 'recipe_form.html', context)
        recipe = form.save(commit=False)
        recipe.author = request.user
        form.save()
        ingedient_names = request.POST.getlist('nameIngredient')
        ingredient_units = request.POST.getlist('unitsIngredient')
        amounts = request.POST.getlist('valueIngredient')
        products = [Product.objects.get(
            title=ingedient_names[i],
            unit=ingredient_units[i]
        ) for i in range(len(ingedient_names))]
        ingredients = []
        for i in range(len(amounts)):
            ingredients.append(Ingredient(
                recipe=recipe, ingredient=products[i], amount=amounts[i]))
        Ingredient.objects.bulk_create(ingredients)
        return redirect('index')


@login_required(login_url='auth/login/')
@require_GET
def get_ingredients(request):
    query = unquote(request.GET.get('query'))

recipes/templates/favorites.html
{% extends 'base.html' %}
{% block title %}Избранное{% endblock %}

{% block styles %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'pages/index.css' %}">
{% endblock %}

{% block content %}
{% csrf_token %}
    <div class="main__header">
        <h1 class="main__title">Избранное</h1>
        {% include 'tags.html' %}
    </div>
    <div class="card-list">
        {% for card in page %}
            {% include 'recipe_card.html' with card=card favorites=page %}
        {% endfor %}
    </div>
    {% include 'paginator.html' with page=page paginator=paginator %}
{% endblock %}
{% block javascript %}
    {% load static %}
    <script src="{% static 'js/components/MainCards.js' %}"></script>
    <script src="{% static 'js/components/Purchpurachases.js' %}"></script>
    <script src="{% static 'js/components/Favorites.js' %}"></script>
    <script src="{% static 'js/components/CardList.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>
    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'js/indexAuth.js' %}"></script>
{% endblock %}

recipes/templates/ingredients_list_form.html
<span> {{ data.ingredient.title }} {{ data.amount }} {{ data.ingredient.unit }}</span>
<span class="form__field-item-delete"></span>
<input id="nameIngredient_{cur}" name="nameIngredient" type="hidden" value="{{ data.title }}">
<input id="valueIngredient_{cur}" name="valueIngredient" type="hidden" value="{{ data.amount }}">
<input id="unitsIngredient_{cur}" name="unitsIngredient" type="hidden" value="{{ data.unit }}">

recipes/templates/profile.html
{% extends 'base.html' %}
{% block title %}Рецепты{% endblock %}

{% block styles %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'pages/index.css' %}">
{% endblock %}

{% block content %}
    <div class="main__header">
        <h1 class="main__title">
            {% if profile.name %}{{ profile.name }}{% else %}{{ profile.username }}{% endif %}
        </h1>
        {% include 'tags.html' %}
    </div>
    {% if request.user.is_authenticated and request.user != profile %}
    <div class="author-subscribe" data-author="{{ profile.id }}">
        <p style="padding: 0 0 2em 0;">
            <button class="button button_style_light-blue button_size_auto" name="subscribe"{% if not is_subscribed %} data-out{% endif %}>{% if is_subscribed %}<span class="icon-check button__icon"></span>Отписаться на автора{% else %}Подписаться на автора{% endif %}</button>
        </p>
    </div>    
    {% endif %}
    <div class="card-list">
        {% for card in page %}
            {% include 'recipe_card.html' with card=card %}
        {% endfor %}
    </div>
    {% include 'paginator.html' with page=page paginator=paginator %}
{% endblock %}
{% block javascript %}
    {% load static %}
        <script src="{% static 'js/components/MainCards.js' %}"></script>
        <script src="{% static 'js/components/Purchpurachases.js' %}"></script>
        <script src="{% static 'js/components/Subscribe.js' %}"></script>
        <script src="{% static 'js/components/Favorites.js' %}"></script>
        <script src="{% static 'js/components/AuthorRecipe.js' %}"></script>
        <script src="{% static 'js/components/Header.js' %}"></script>
        <script src="{% static 'js/api/Api.js' %}"></script>
        <script src="{% static 'js/authorRecipe.js' %}"></script>

{% endblock %}

recipes/templates/purchases.html
{% extends 'base.html' %}
{% block title %}Список покупок{% endblock %}

{% block styles %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'pages/shopList.css' %}">
{% endblock %}

{% block content %}
    {% load thumbnail %}
    {% csrf_token %}
    <div class="main__header">
        <h1 class="main__title">Список покупок</h1>
    </div>
    <div class="card-list card-list_column">
        <ul class="shopping-list">
            {% for recipe in recipes_list %}
                <li class="shopping-list__item" data-id="{{ recipe.id }}">
                    <div class="recipe recipe_reverse">
                        {% thumbnail recipe.image "90x90" crop="center" upscale=True as im %}
                            <img src="{{ im.url }}" alt="{{ recipe.name }}" class="recipe__image recipe__image_big">
                        {% endthumbnail %}
                        <h2 class="recipe__title">{{ recipe.name }}</h2>
                        <p class="recipe__text"><span class="icon-time"></span> {{ recipe.cook_time }} мин.</p>
                    </div>
                    <button class="shopping-list__button link">Удалить</button>
                </li>
            {% endfor %}
        </ul>
        {% if recipes_list %}
            <a class="button button_style_blue" href="{% url 'shop-list' %}">Скачать список</a>
        {% endif %}
    </div>
{% endblock %}

{% block javascript %}
    {% load static %}
    <script src="{% static 'js/components/Header.js' %}"></script>
    <script src="{% static 'js/components/ShopList.js' %}"></script>
    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'js/shopList.js' %}"></script>
{% endblock %}

recipes/templates/recipe_card.html
{% load thumbnail user_filters %}
{% csrf_token %}
<div class="card" data-id="{{ card.id }}">
    <a href="{% url 'recipe' recipe_id=card.id %}" class="link">
        {% thumbnail card.image "364x240" crop="center" upscale=True as im %}
        <img src="{{ im.url }}" alt="{{ card.name }}" width="100%" height="{{ im.height}}" class="card__image">
        {% endthumbnail %}
    </a>
    <div class="card__body">
        <a class="card__title link" href="{% url 'profile' user_id=card.author.id %}">{{ card.name }}</a>
        <ul class="card__items">
            {% for tag in card.tags.all %}
            <li class="card__item"><span class="badge badge_style_{{ tag|add_color }}">{{ tag.name }}</span></li>
            {% endfor %}
        </ul>
        <div class="card__items card__items_column">
            <p class="card__text"><span class="icon-time"></span> {{ card.cook_time }} мин.</p>
            <p class="card__text"><span class="icon-user"></span> <a href="{% url 'profile' user_id=card.author.id %}" style="color: black">{{ card.author }}</a></p>
        </div>
    </div>
    <div class="card__footer">
        {% if request.user.is_authenticated %}
            <button class="button button_style_light-blue" name="purchpurchases" {% if card not in purchase_list %}data-out{% endif %}><span class="{% if card in purchase_list %}icon-check{% else %}icon-plus{% endif %} button__icon"></span>{% if card in purchase_list %}Рецепт добавлен{% else %}Добавить в покупки{% endif %}</button>
            <button class="button button_style_none" name="favorites"{% if card not in favorites %} data-out{% endif %}><span class="icon-favorite{% if card in favorites %} icon-favorite_active{% endif %}"></span></button>
        {% endif %}
    </div>
</div>

recipes/templates/recipe_detail.html
{% extends 'base.html' %}
{% block title %}{{ recipe.name }}{% endblock %}

{% block styles %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'pages/single.css' %}">
{% endblock %}

{% block content %}
{% csrf_token %}
{% load thumbnail user_filters %}
    <div class="single-card" data-id="{{ recipe.id }}" data-author="{{ recipe.author.id }}">
        {% thumbnail recipe.image '480x480' crop="center" upscale=True as im %}
        <img src="{{ im.url }}" alt="recipe.name" width="480" height="480" class="single-card__image">
        {% endthumbnail %}
        <div class="single-card__info">
            <div class="single-card__header-info">
                <h1 class="single-card__title">{{ recipe.name }}</h1>
                {% if request.user.is_authenticated %}
                    <div class="single-card__favorite">
                        <button class="button button_style_none" name="favorites"{% if recipe not in favorites %} data-out{% endif %}><span class="icon-favorite icon-favorite_big{% if recipe in favorites %} icon-favorite_active{% endif %}"></span></button>
                        <div class="single-card__favorite-tooltip tooltip">Добавить в избранное</div>
                    </div>
                {% endif %}
            </div>
            <ul class="single-card__items">
                {% for tag in recipe.tags.all %}
                    <li class="single-card__item"><span class="badge badge_style_{{ tag|add_color }}">{{ tag.name }}</span></li>
                {% endfor %}
            </ul>
            <div class="single-card__items single-card__items_column">
                <p class="single-card__text"><span class="icon-time"></span> {{ recipe.cook_time }} мин.</p>
                {% if request.user.is_authenticated %}
                    <ul class="single-card__items">
                        <li class="single-card__item"><p class="single-card__text"><span class="icon-user"></span>{{ recipe.author }}</p></li>
                        {% if request.user == recipe.author %}
                            <li class="single-card__item">  <a style="margin-left: 2.5em" href="{% url 'edit_recipe' recipe_id=recipe.id %}" class="single-card__text">Редактировать рецепт</a></li>
                        {% endif %}
                    </ul>
                {% else %}
                    <p class="single-card__text"><span class="icon-user"></span> {{ recipe.author }}</p>
                {% endif %}
            </div>
            <ul class="single-card__items">
                {% if request.user.is_authenticated %}
                    <li class="single-card__item"><button class="button{% if is_purchased %} button_style_light-blue-outline{% else %} button_style_blue{% endif %}" name="purchpurchases"{% if recipe not in purchase_list %} data-out{% endif %}><span class="{% if recipe in purchase_list %}icon-check{% else %}icon-plus{% endif %} button__icon"></span>{% if recipe in purchase_list %}Рецепт добавлен{% else %}Добавить в покупки{% endif %}</button></li>
                {% endif %}
                {% if request.user.is_authenticated and request.user != recipe.author %}
                    <li class="single-card__item" data-id="{{ recipe.author.id }}"><button class="button button_style_light-blue button_size_auto{% if is_subscribed %} button_style_light-blue-outline{% endif %}" name="subscribe"{% if not is_subscribed %} data-out{% endif %}>{% if is_subscribed %}Отписаться от автора{% else %}Подписаться на автора{% endif %}</button></li>
                {% endif %}
            </ul>
            <div class="single-card__section">
                <h3 class="single-card__section-title">Ингридиенты:</h3>
                <div class="single-card__items single-card__items_column">
                    {% for ingredient in recipe.ingredient_set.all %}
                    <p class=" single-card__section-item">{{ ingredient.ingredient.title }} - {{ ingredient.amount }} {{ ingredient.ingredient.unit }}</p>
                    {% endfor %}
                </div>
            </div>
            <div class="single-card__section">
                <h3 class="single-card__section-title">Описание:</h3>
                <p class="single-card__section-text">{{ recipe.description }}</p>
            </div>
        </div>
    </div>
{% endblock %}
{% block javascript %}
    {% load static %}
    <script src="{% static 'js/components/Purchpurachases.js' %}"></script>
    <script src="{% static 'js/components/Subscribe.js' %}"></script>
    <script src="{% static 'js/components/Favorites.js' %}"></script>

    <script src="{% static 'js/components/MainCards.js' %}"></script>
    <script src="{% static 'js/components/SingleCard.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>
    
    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'js/singlePage.js' %}"></script>
{% endblock %}

recipes/templates/subscription_card.html
{% load thumbnail user_filters %}
<div class="card-user" data-author="{{ card.author.id }}">
    <div class="card-user__header">
        <h2 class="card-user__title">{{ card.author }}</h2>
    </div>
    <div class="card-user__body">
        <ul class="card-user__items">
            {% for recipe in card.author.recipe_author.all %}
                {% if forloop.counter < 4 %}    
                    <li class="card-user__item">
                        <div class="recipe">
                            {% thumbnail recipe.image "72x72" crop="center" upscale=True as im %}
                            <img src="{{ im.url }}" alt="{{ recipe.name }}" class="recipe__image">
                            {% endthumbnail %}
                            <h3 class="recipe__title">{{ recipe.name }}</h3>
                            <p class="recipe__text"><span class="icon-time"></span> {{ recipe.cook_time }} мин.</p>
                        </div>
                    </li>
                {% endif %}
            {% endfor %}
            {% if card.author.recipe_author.count > 3 %}
                <li class="card-user__item">
                    <a href="{% url 'profile' user_id=card.author.id %}" class="card-user__link link">Еще {{ card.author.recipe_author.count|subtract:'3' }} рецептов...</a>
                </li>
            {% endif %}
        </ul>
    </div>
    <div class="card-user__footer">
        <button class="button button_style_light-blue button_size_auto" name="subscribe">Отписаться</button>
    </div>
</div>